---
Title: "Effect of knot: cq.reg"
author: ""
date: ""
---

```{r, include=F}
devtools::load_all()
```

# Simulated Data Examples
```{r simulation function, include=F}
set.seed(202104)
n <- 400
x <- runif(n)
ord <- order(x)
x_ord <- x[ord]
sigma <- 0.4 * (0.5 + x)
residual <- rnorm(n, mean = rep(0, n), sd = sigma)
# linear
f1 <- function(x) {
    0.2 + 0.4 * x
}
# logarithm
f2 <- function(x) {
    log(x)
}
# sinusoidal
f3 <- function(x) {
    sin(2 * pi * x)
}
# square root sinusoidal
f4 <- function(x) {
    sqrt(x * (1 - x)) * sin(2 * pi * (1 + 2 ^ (-7 / 5)) / (x + 2 ^ (-7 / 5)))
}

# non-crosing QR
f <- function(i, arg_bs = c("tesmi2", "cr"), opt = "efs", knots = c(10, 10),
                span = 0.1, bandwidth=NULL, rnn=NULL, knn=NULL,
                analysis = F, visual = T, compare = T, draw_compare = F, ...) {
    if (i == 1) {
        y <- f1(x) + residual
        y_ord <- f1(x_ord)
    }
    if (i == 2) {
        y <- f2(x) + residual
        y_ord <- f2(x_ord)
    }
    if (i == 3) {
        y <- f3(x) + residual
        y_ord <- f3(x_ord)
    }
    if (i == 4) {
        y <- f4(x) + residual
        y_ord <- f4(x_ord)
    }

    fit <- cq.reg(x, y, bivar = T, arg_bs,
                opt, knots,
                span, bandwidth, rnn, knn,
                analysis
                )
    if (analysis) {
        print(summary(fit))
    }

    if (visual) {
        cq_plot(fit, ...)
    }

    ## l2loss
    L2loss <- matrix(rep(0, 9), nrow = 1)
    colnames(L2loss) <- (1:9) / 10
    if (compare) {
        for (i in 1:9) {
            tau <- i / 10
            curve <- predict(fit, data.frame(x1 = x_ord, tau = tau))
            truth <- y_ord + qnorm(tau, mean = rep(0, n), sd = sigma)[ord]
            diff <- curve - truth
            L2loss[1, i] <- mean(diff^2)
            if (draw_compare) {
                dev.new()
                plot(x_ord, y_ord)
                lines(x_ord, truth, col = 2)
                lines(x_ord, curve, col = 3)
            }
        }
    }

    return(L2loss)
}
```

## logarithm log(x) with span = 0.05
#### knots = $\{(5, 5), (10, 5), (10, 10), (15, 5), (15, 10), (15, 15), (20, 5), (20, 10)\}$
```{r simulation1, out.width = "100%", fig.dim = c(12, 12)}
v_knots <- list(c(5, 5), c(10, 5), c(10, 10),
                c(15, 5), c(15, 10), c(15, 15),
                c(20, 5), c(20, 10))
par(mfrow = c(2, 2))
m_loss <- matrix(0, nrow = length(v_knots), ncol = 9)
colnames(m_loss) <- paste0("tau=", (1:9) / 10)
rownames(m_loss) <- paste0("knots=", v_knots)
for (i in seq_along(v_knots)) {
    knots <- v_knots[[i]]
    m_loss[i, ] <- f(2, arg_bs = c("tedmi"), span = 0.05, knots = knots,
        main = paste("knots=", knots))
}
```

### L2 loss
```{r}
round(m_loss, 5)
round(rowMeans(m_loss), 5)
```

## logarithm log(x) with rnn = 0.05
#### knots = $\{(5, 5), (10, 5), (10, 10), (15, 5), (15, 10), (15, 15), (20, 5), (20, 10)\}$
```{r simulation2, out.width = "100%", fig.dim = c(12, 12)}
v_knots <- list(c(5, 5), c(10, 5), c(10, 10),
                c(15, 5), c(15, 10), c(15, 15),
                c(20, 5), c(20, 10))
par(mfrow = c(2, 2))
m_loss <- matrix(0, nrow = length(v_knots), ncol = 9)
colnames(m_loss) <- paste0("tau=", (1:9) / 10)
rownames(m_loss) <- paste0("knots=", v_knots)
for (i in seq_along(v_knots)) {
    knots <- v_knots[[i]]
    m_loss[i, ] <- f(2, arg_bs = c("tedmi"),
                    span = NULL, rnn = 0.05, knots = knots,
                    main = paste("knots=", knots))
}
```

### L2 loss
```{r}
round(m_loss, 5)
round(rowMeans(m_loss), 5)
```





## square root sinusoidal with span = 0.03
#### $\sqrt{x (1 - x)}  \sin(2  \pi  (1 + 2^{-7 / 5}) / (x + 2^{-7 / 5}))$
#### knots = $\{(5, 5), (10, 5), (10, 10), (15, 5), (15, 10), (15, 15), (20, 5), (20, 10)\}$
```{r simulation3, out.width = "100%", fig.dim = c(12, 12)}
v_knots <- list(c(5, 5), c(10, 5), c(10, 10),
                c(15, 5), c(15, 10), c(15, 15),
                c(20, 5), c(20, 10))
par(mfrow = c(2, 2))
m_loss <- matrix(0, nrow = length(v_knots), ncol = 9)
colnames(m_loss) <- paste0("tau=", (1:9) / 10)
rownames(m_loss) <- paste0("knots=", v_knots)
for (i in seq_along(v_knots)) {
    knots <- v_knots[[i]]
    m_loss[i, ] <- f(4, span = 0.03, knots = knots,
        main = paste("knots=", knots))
}
```

### L2 loss
```{r}
round(m_loss, 5)
round(rowMeans(m_loss), 5)
```


## square root sinusoidal with rnn = 0.05
#### $\sqrt{x (1 - x)}  \sin(2  \pi  (1 + 2^{-7 / 5}) / (x + 2^{-7 / 5}))$
#### knots = $\{(5, 5), (10, 5), (10, 10), (15, 5), (15, 10), (15, 15), (20, 5), (20, 10)\}$
```{r simulation4, out.width = "100%", fig.dim = c(12, 12)}
v_knots <- list(c(5, 5), c(10, 5), c(10, 10),
                c(15, 5), c(15, 10), c(15, 15),
                c(20, 5), c(20, 10))
par(mfrow = c(2, 2))
m_loss <- matrix(0, nrow = length(v_knots), ncol = 9)
colnames(m_loss) <- paste0("tau=", (1:9) / 10)
rownames(m_loss) <- paste0("knots=", v_knots)
for (i in seq_along(v_knots)) {
    knots <- v_knots[[i]]
    m_loss[i, ] <- f(4, span = NULL, rnn = 0.05, knots = knots,
        main = paste("knots=", knots))
}
```

### L2 loss
```{r}
round(m_loss, 5)
round(rowMeans(m_loss), 5)
```