---
Title: "Presentation: cq.reg"
author: ""
date: ""
---

```{r, include=F}
devtools::load_all()
library(parallel)
```

```{r loading, include=F}
load("sim_tunedefault.RData")
taus <- seq(0.05, 0.95, length.out = 7)
```


```{r tune1 draw, out.width = "100%", fig.dim = c(8, 4)}
v_gmean <- c("linear", "log", "sin", "lsin", "sqrtsin")
v_xsig <- c("const", "linear", "quad")
v_derr <- c("norm", "chisq3", "t3", "t1")
par(mfrow = c(1, 2))
l_better <- list()
for (gmean in seq_along(v_gmean)) {
    for (xsig in seq_along(v_xsig)) {
        for (derr in seq_along(v_derr)) {
            tunning <- tune[[gmean]][[xsig]][[derr]]
            if (!is.atomic(tunning)) {
                main <- paste(v_gmean[gmean], v_xsig[xsig], v_derr[derr])
                cq_regplot(tunning$model[[1]], sub = "gam", main = main)
                x <- tunning$model[[1]]$x
                for (tau in taus) {
                    truth <- truth_f(x, tau,
                            gmean = gmean, xsig = xsig, derr = derr)
                    lines(x, truth, col = "grey")
                }
                cq_regplot(tunning$model[[2]], sub = "scam", main = main)
                for (tau in taus) {
                    truth <- truth_f(x, tau,
                            gmean = gmean, xsig = xsig, derr = derr)
                    lines(x, truth, col = "grey")
                }
                print("MSE:")
                v_mse <- rowMeans(tunning$L2loss)[1:2]
                print(v_mse)
                print("Time:")
                print((tunning$time)[1:2, ])
                if (v_mse[1] >= v_mse[2]) {
                    l_better[[length(l_better) + 1]] <- main
                }
            } else {
                print(0)
            }
        }
    }
}
l_better
```



